### ISSUE TITLE
Issues Nanoleaf forum rowak

### ISSUE THREAD

**Issue by StijnOostdam** [StijnOostdam/Winleafs#30]
Your app looks great! This kind of application is more useful for me than the Nanoleaf mobile app, since I'm always at my computer.

First of all I loved the device setup process. It worked perfectly! However, after the setup I ran into a few problems (using v0.1.2):

- The schedules don't seem to actually work. I might be doing something wrong, but no matter what schedules I set, the panels just toggle between on and off every 30 seconds or so.
- The combo boxes for selecting effects display the names of each of my effects 27 times instead of once for each effect.
- The "manage schedule" window that appears after clicking the "+" button in the main form doesn't scale to my display (2160x1440) causing both sides of the window to be off-screen.
- The UI doesn't resize very well in the main form. Some components are static and others are hidden by random spacing.

**Comment by bartdebever** [comment]
> * The UI doesn't resize very well in the main form. Some components are static and others are hidden by random spacing.

Fixed in the translations branch under b258ad7aa946382787e492a8ba9fbf664a4f203d

UI elements now need to be spaced depending on which side they are on and given proper margins.
If an element is spaced with the left it doesn't get a margin to the right, same for up and down.

**Comment by rowak** [comment]
Sorry this is a bit late. Here's some screenshots and info that might help:

https://i.ibb.co/b5YzP0p/issue1.png - This is an example of a schedule I set, but nothing seems to happen when 11:00 comes around. Also note that since the latest release, the toggling between effects every 30 seconds seems to have stopped!

https://i.ibb.co/2sMqYtT/issue2.png - This seems to happen for every combo box containing effects.

https://i.ibb.co/1X4RBm1/issue3.png - This is the schedule window that pops up when clicking the "+" button on the main window. The image shows the entire width of my monitor which is 2160x1440.

**Comment by StijnOostdam** [comment]
Thank you for the pictures. Reagarding issue 3, I hope this is fixed in the next release as we will have scalable UI. 

In the current release of https://github.com/StijnOostdam/Winleafs/releases/tag/v0.3 you can delete a device. Could you try deleting and adding your device and see if you still have the large list of effects? If so, could you post your logs (found under AppData\Roaming\Winleafs\logs\log.log), we probably send some weird requests I expect.

As for your first issue: if you experience weird behavior again, could you post your logs? Then we can see why it is behaving weird.

Thanks for your help!

**Comment by rowak** [comment]
Looks like that solved it! The effects are now displaying properly and the schedules started working properly as well.

**Comment by StijnOostdam** [comment]
Great to hear. Marking this as closed then.
